project:
  type: website

website:
  title: "Prompts, Dreams, and Me"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hanxi-guo
      - icon: linkedin
        href: https://www.linkedin.com/in/hanxi-guo-765289301/
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


