project:
  type: website

website:
  title: "About My Explorations with LLMs（test blog)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto


